routerAdd('GET', '/bi/sellers/{id}/inactive-customers', (e) => {
  const sellerId = e.request.pathValue('id') || 'current'
  const now = new Date()
  const syncedAt = now.toISOString()
  const sourceUpdatedAt = new Date(now.getTime() - 25 * 60 * 1000).toISOString()

  const customers = [
    {
      customerId: 'CLI-8041',
      customerName: 'Metalúrgica Santa Rita Ltda',
      cnpj: '45.182.903/0001-44',
      segment: 'Estruturas Metálicas',
      city: 'Campinas',
      uf: 'SP',
      sellerId: sellerId,
      sellerName: 'Carlos Mendonça',
      lastPurchaseDate: '2024-08-14',
      daysSinceLastPurchase: 74,
      historicalRevenue: 485000,
      historicalTons: 62.5,
      ticket: 48500,
      frequency: 45,
      recurrenceMonths: [1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
      pAlive: 0.82,
      expectedNextPurchaseDays: 6,
      expectedValue: 54000,
      reactivationScore: 94,
      rfmSegment: 'Em risco',
      creditLimit: 120000,
      creditAvailable: 95000,
      creditStatus: 'liberado',
      stockCoveragePercent: 96,
      recommendedAction: 'Ofertar Tubos Inox 304 com pronta-entrega (preço FOB especial)',
      recommendedChannel: 'whatsapp',
      reason:
        '74 dias sem compras. Recorrência histórica de 45 dias. Estoque de tubos 304 em alta cobertura.',
    },
    {
      customerId: 'CLI-7910',
      customerName: 'Caldeiraria & Tanques Industrial Paulista',
      cnpj: '12.894.210/0001-92',
      segment: 'Equipamentos Químicos e Alimentícios',
      city: 'Sertãozinho',
      uf: 'SP',
      sellerId: sellerId,
      sellerName: 'Carlos Mendonça',
      lastPurchaseDate: '2024-07-19',
      daysSinceLastPurchase: 102,
      historicalRevenue: 890000,
      historicalTons: 115.0,
      ticket: 89000,
      frequency: 35,
      recurrenceMonths: [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
      pAlive: 0.78,
      expectedNextPurchaseDays: 4,
      expectedValue: 98000,
      reactivationScore: 91,
      rfmSegment: 'Campeões',
      creditLimit: 250000,
      creditAvailable: 210000,
      creditStatus: 'liberado',
      stockCoveragePercent: 92,
      recommendedAction: 'Ligar para Diretor de Suprimentos: pacote Chapas Inox 316L para safra',
      recommendedChannel: 'telefone',
      reason:
        'Grande conta com quebra abrupta após manutenção anual. Histórico de compras volumosas.',
    },
    {
      customerId: 'CLI-6523',
      customerName: 'Indústria Mecânica Alvorada S/A',
      cnpj: '03.771.820/0002-18',
      segment: 'Autopeças & Implementos',
      city: 'Joinville',
      uf: 'SC',
      sellerId: sellerId,
      sellerName: 'Carlos Mendonça',
      lastPurchaseDate: '2024-08-30',
      daysSinceLastPurchase: 61,
      historicalRevenue: 340000,
      historicalTons: 48.0,
      ticket: 34000,
      frequency: 30,
      recurrenceMonths: [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
      pAlive: 0.85,
      expectedNextPurchaseDays: 3,
      expectedValue: 42000,
      reactivationScore: 89,
      rfmSegment: 'Leais',
      creditLimit: 150000,
      creditAvailable: 150000,
      creditStatus: 'liberado',
      stockCoveragePercent: 88,
      recommendedAction: 'Apresentar condições de Barras Laminadas 1045 e Inox 410',
      recommendedChannel: 'whatsapp',
      reason: 'Comprador habitual de início de mês; atraso de 30 dias no pedido recorrente.',
    },
  ]

  return e.json(200, {
    seller_id: sellerId,
    total: customers.length,
    items: customers,
    is_demo_data: true,
    source_updated_at: sourceUpdatedAt,
    synced_at: syncedAt,
  })
})
