// src/modules/crm360/providers/index.ts
// Re-exportação dos provedores de integração externa do CRM 360 CIAFAL
export * from '@/providers/index'
export * from '@/providers/types'
export * from '@/providers/ERPProvider'
export * from '@/providers/SAPCreditProvider'
export * from '@/providers/TMSProvider'
export * from '@/providers/AIProvider'
export * from '@/providers/BIProvider'
export * from '@/providers/QlikProvider'
export * from '@/providers/GeoProvider'
export * from '@/providers/IdentityProvider'
export * from '@/providers/DigitalSignatureProvider'
export * from '@/providers/DocuSignProvider'
export * from '@/providers/D4SignProvider'
export * from '@/providers/Microsoft365Provider'
export * from '@/providers/MicrosoftGraphProvider'
export * from '@/providers/WhatsAppProvider'
export * from '@/providers/NotificationProvider'
export * from '@/providers/TelephonyProvider'
export * from '@/providers/FileStorageProvider'
export * from '@/providers/LocalAIAdapter'
